version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py load_data_to_db &&
            python3 manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=comic_store
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=comic_store
      - POSTGRES_HOST=db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
