# Generated by Django 4.1.3 on 2022-12-02 19:36
import os
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    def generate_user(apps, schema_editor):
        from django.contrib.auth.models import User

        DJANGO_SU_NAME = os.environ.get('DJANGO_SU_NAME')
        DJANGO_SU_EMAIL = os.environ.get('DJANGO_SU_EMAIL')
        DJANGO_SU_PASSWORD = os.environ.get('DJANGO_SU_PASSWORD')

        superuser = User.objects.create_superuser(
            username=DJANGO_SU_NAME,
            email=DJANGO_SU_EMAIL,
            password=DJANGO_SU_PASSWORD)

        superuser.save()

    #     generate token for superuser
        from rest_framework.authtoken.models import Token
        Token.objects.create(user=superuser)

    operations = [
        migrations.AlterField(
            model_name="comic",
            name="day",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="comic",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="comic",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="comic",
            name="issue",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="comic",
            name="month",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="comic",
            name="year",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
